default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cocoktail_api_development
  
test:
  <<: *default
  database: cocoktail_api_test

production:
  <<: *default
  database: cocoktail_api_production
  username: cocoktail_api
  password: <%= ENV['COCOKTAIL_API_DATABASE_PASSWORD'] %>
